### ISSUE TITLE
how to add data to the input-dropdown

### ISSUE THREAD

**Issue by g-londhe** [CoffeeBeansLabs/react-native-form-builder#2]
{
        component: 'input-dropdown',
        field_name: 'fees_paid_by',
        is_mandatory: 'true',
          data: [ // This is the data I'm trying to add
                {
                  label: 'dd_1',
                  value: "Drop_down_1"
                },
                {
                    label: 'dd_2',
                    value: "Drop_down_2"
                  },
          ]
      },

**Comment by pillaigrshma** [comment]
The field name needs to be `items` instead of `data`. You can check the example [here](https://github.com/CoffeeBeansLabs/react-native-form-builder/blob/master/examples/sample.js#L91). (Sorry for the delayed response.)
